import { test, expect } from '@playwright/test'
import demo from '../../public/site.config.json' with { type: 'json' }
import { configSchema } from '../../shared/config'
import { initialPages, pagesSchema, type PageDocument } from '../../shared/pages'

test('color picker and independent Markdown sections survive saving and reload', async ({ page }) => {
  let document: PageDocument = initialPages(configSchema.parse(demo))
  await page.route('**/__edit/api/pages', async route => {
    if (route.request().method() === 'POST') {
      document = pagesSchema.parse(route.request().postDataJSON())
      await route.fulfill({ json: { ok: true } })
    } else await route.fulfill({ json: document })
  })
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/__edit/')
  const name = page.locator('[data-edit-text="profile.name"]')
  await name.click()
  await page.getByLabel('调整文字颜色', { exact: true }).click()
  const hex = page.getByRole('textbox', { name: '文字颜色色码', exact: true })
  await hex.fill('#7856c8'); await hex.press('Tab')
  await expect(name).toHaveCSS('color', 'rgb(120, 86, 200)')
  await hex.fill('wrong'); await hex.press('Tab')
  await expect(page.getByRole('alert')).toContainText('十六进制')
  await expect(name).toHaveCSS('color', 'rgb(120, 86, 200)')
  await page.getByRole('button', { name: '恢复默认颜色' }).click()
  await expect(name).toHaveCSS('color', 'rgb(36, 40, 34)')
  await page.getByLabel('文字颜色拾色器', { exact: true }).fill('#31856c')
  await expect(name).toHaveCSS('color', 'rgb(49, 133, 108)')
  await page.getByRole('button', { name: '页面设置与访问路由' }).click()
  await page.getByLabel('调整正文文字色', { exact: true }).click()
  await page.getByLabel('正文文字色色码', { exact: true }).fill('246')
  await page.getByLabel('正文文字色色码', { exact: true }).press('Tab')
  await expect(page.locator('.preview-viewport')).toHaveCSS('color', 'rgb(34, 68, 102)')
  for (const [title, content] of [['第一篇', '## 独立模块一\n\n**实时预览**\n\n- 第一条'], ['第二篇', '## 独立模块二\n\n[内部链接](/about/)']]) {
    await page.getByRole('button', { name: '添加', exact: true }).click()
    await page.getByRole('button', { name: '添加Markdown', exact: true }).click()
    await page.getByLabel('模块名称', { exact: true }).fill(title)
    await page.getByLabel('Markdown 内容', { exact: true }).fill(content)
    await page.getByRole('button', { name: '预览 Markdown', exact: true }).click()
  }
  await expect(page.locator('.markdown-section')).toHaveCount(2)
  await expect(page.locator('.markdown-section').first().locator('strong')).toHaveText('实时预览')
  await page.getByLabel('调整模块文字颜色', { exact: true }).click()
  await page.getByLabel('模块文字颜色色码', { exact: true }).fill('#DC4965')
  await page.getByLabel('模块文字颜色色码', { exact: true }).press('Tab')
  await expect(page.locator('.markdown-section').last()).toHaveCSS('color', 'rgb(220, 73, 101)')
  await page.getByRole('button', { name: '上移当前模块' }).click()
  await expect(page.locator('.markdown-section').first()).toContainText('独立模块二')
  await page.getByRole('button', { name: '保存全部页面', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('已保存。')
  expect(document.pages[0].config.textColors['profile.name']).toBe('#31856C')
  expect(Object.keys(document.pages[0].config.markdownBlocks)).toHaveLength(2)
  await page.reload()
  await expect(name).toHaveCSS('color', 'rgb(49, 133, 108)')
  await expect(page.locator('.markdown-section').first()).toContainText('独立模块二')
  await page.locator('.markdown-section').last().click()
  await expect(page.getByLabel('模块名称', { exact: true })).toHaveValue('第一篇')
  await page.getByRole('button', { name: '移除当前模块' }).click()
  await expect(page.locator('.markdown-section')).toHaveCount(1)
  await expect(page.locator('.markdown-section')).toContainText('独立模块二')
  await page.getByRole('button', { name: '第二篇', exact: true }).click()
  await page.screenshot({ path: 'test-results/markdown-color-editor.png' })
})

test('clicking a Markdown block opens a focused canvas editor with preview and formatting', async ({ page }) => {
  let document = initialPages(configSchema.parse(demo))
  document.pages[0].config.markdownBlocks['markdown-test'] = { name: '写作模块', content: '## 点击编辑\n\n保留原有内容', textColor: '', background: '' }
  document.pages[0].layout.push('markdown-test')
  await page.route('**/__edit/api/pages', async route => {
    if (route.request().method() === 'POST') { document = pagesSchema.parse(route.request().postDataJSON()); await route.fulfill({ json: { ok: true } }) }
    else await route.fulfill({ json: document })
  })
  await page.goto('/__edit/')
  const block = page.locator('.markdown-section')
  await block.getByRole('heading', { name: '点击编辑' }).click()
  const source = block.getByRole('textbox', { name: 'Markdown 内容', exact: true })
  await expect(source).toBeFocused()
  await expect(source).toHaveValue('## 点击编辑\n\n保留原有内容')
  await source.fill('## 画布编辑\n\n新的内容')
  await page.getByRole('button', { name: '预览 Markdown', exact: true }).click()
  await expect(source).toHaveCount(0)
  await expect(block.getByRole('heading', { name: '画布编辑' })).toBeVisible()
  await block.getByRole('heading', { name: '画布编辑' }).click()
  await expect(source).toBeFocused()
  await source.fill('格式测试')
  await source.press('Control+a')
  await block.getByRole('button', { name: '粗体', exact: true }).click()
  await expect(source).toHaveValue('**格式测试**')
  await source.press('Escape')
  await expect(block.locator('.markdown-content strong')).toHaveText('格式测试')
  await page.getByRole('button', { name: '保存全部页面', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('已保存。')
  await page.reload()
  await expect(block.locator('.markdown-content strong')).toHaveText('格式测试')
  await block.locator('.markdown-content').click()
  await page.screenshot({ path: 'test-results/markdown-canvas-editor.png' })
})
